// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace EthereumSamuraiApiCaller.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Erc20BalanceResponse
    {
        /// <summary>
        /// Initializes a new instance of the Erc20BalanceResponse class.
        /// </summary>
        public Erc20BalanceResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Erc20BalanceResponse class.
        /// </summary>
        public Erc20BalanceResponse(long blockNumber, string address = default(string), string amount = default(string), string contract = default(string))
        {
            Address = address;
            Amount = amount;
            BlockNumber = blockNumber;
            Contract = contract;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public string Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "blockNumber")]
        public long BlockNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contract")]
        public string Contract { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
