// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace EthereumSamuraiApiCaller.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class InternalMessageResponse
    {
        /// <summary>
        /// Initializes a new instance of the InternalMessageResponse class.
        /// </summary>
        public InternalMessageResponse()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InternalMessageResponse class.
        /// </summary>
        public InternalMessageResponse(string transactionHash = default(string), long? blockNumber = default(long?), string fromAddress = default(string), string toAddress = default(string), int? depth = default(int?), string value = default(string), int? messageIndex = default(int?), string type = default(string), int? blockTimeStamp = default(int?))
        {
            TransactionHash = transactionHash;
            BlockNumber = blockNumber;
            FromAddress = fromAddress;
            ToAddress = toAddress;
            Depth = depth;
            Value = value;
            MessageIndex = messageIndex;
            Type = type;
            BlockTimeStamp = blockTimeStamp;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionHash")]
        public string TransactionHash { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "blockNumber")]
        public long? BlockNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fromAddress")]
        public string FromAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "toAddress")]
        public string ToAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "depth")]
        public int? Depth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "messageIndex")]
        public int? MessageIndex { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "blockTimeStamp")]
        public int? BlockTimeStamp { get; set; }

    }
}
