// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.EthereumCore.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AddressTokenBalanceContainerResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// AddressTokenBalanceContainerResponse class.
        /// </summary>
        public AddressTokenBalanceContainerResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// AddressTokenBalanceContainerResponse class.
        /// </summary>
        public AddressTokenBalanceContainerResponse(IList<AddressTokenBalanceResponse> balances = default(IList<AddressTokenBalanceResponse>))
        {
            Balances = balances;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "balances")]
        public IList<AddressTokenBalanceResponse> Balances { get; set; }

    }
}
