// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.EthereumCore.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BalanceModel
    {
        /// <summary>
        /// Initializes a new instance of the BalanceModel class.
        /// </summary>
        public BalanceModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BalanceModel class.
        /// </summary>
        public BalanceModel(string amount = default(string))
        {
            Amount = amount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public string Amount { get; set; }

    }
}
