// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.EthereumCore.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CheckSignResponse
    {
        /// <summary>
        /// Initializes a new instance of the CheckSignResponse class.
        /// </summary>
        public CheckSignResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CheckSignResponse class.
        /// </summary>
        public CheckSignResponse(bool? signIsCorrect = default(bool?))
        {
            SignIsCorrect = signIsCorrect;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "signIsCorrect")]
        public bool? SignIsCorrect { get; set; }

    }
}
