// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.EthereumCore.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CoinResult
    {
        /// <summary>
        /// Initializes a new instance of the CoinResult class.
        /// </summary>
        public CoinResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CoinResult class.
        /// </summary>
        public CoinResult(int multiplier, bool blockchainDepositEnabled, bool containsEth, string blockchain = default(string), string id = default(string), string name = default(string), string adapterAddress = default(string), string externalTokenAddress = default(string))
        {
            Blockchain = blockchain;
            Id = id;
            Name = name;
            AdapterAddress = adapterAddress;
            ExternalTokenAddress = externalTokenAddress;
            Multiplier = multiplier;
            BlockchainDepositEnabled = blockchainDepositEnabled;
            ContainsEth = containsEth;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Blockchain")]
        public string Blockchain { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdapterAddress")]
        public string AdapterAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalTokenAddress")]
        public string ExternalTokenAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Multiplier")]
        public int Multiplier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BlockchainDepositEnabled")]
        public bool BlockchainDepositEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContainsEth")]
        public bool ContainsEth { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
