// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.EthereumCoreClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GetErcBalance
    {
        /// <summary>
        /// Initializes a new instance of the GetErcBalance class.
        /// </summary>
        public GetErcBalance()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetErcBalance class.
        /// </summary>
        public GetErcBalance(string address = default(string), IList<string> tokenAddresses = default(IList<string>))
        {
            Address = address;
            TokenAddresses = tokenAddresses;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tokenAddresses")]
        public IList<string> TokenAddresses { get; set; }

    }
}
