// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.EthereumCore.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HotWalletCashoutRequest
    {
        /// <summary>
        /// Initializes a new instance of the HotWalletCashoutRequest class.
        /// </summary>
        public HotWalletCashoutRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HotWalletCashoutRequest class.
        /// </summary>
        public HotWalletCashoutRequest(string operationId = default(string), string fromAddress = default(string), string toAddress = default(string), string amount = default(string), string tokenAddress = default(string))
        {
            OperationId = operationId;
            FromAddress = fromAddress;
            ToAddress = toAddress;
            Amount = amount;
            TokenAddress = tokenAddress;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OperationId")]
        public string OperationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FromAddress")]
        public string FromAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ToAddress")]
        public string ToAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public string Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TokenAddress")]
        public string TokenAddress { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Amount != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(Amount, "^[1-9][0-9]*$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "Amount", "^[1-9][0-9]*$");
                }
            }
        }
    }
}
