// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.EthereumCore.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PrivateWalletEthSignedTransaction
    {
        /// <summary>
        /// Initializes a new instance of the PrivateWalletEthSignedTransaction
        /// class.
        /// </summary>
        public PrivateWalletEthSignedTransaction()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PrivateWalletEthSignedTransaction
        /// class.
        /// </summary>
        public PrivateWalletEthSignedTransaction(string fromAddress = default(string), string signedTransactionHex = default(string))
        {
            FromAddress = fromAddress;
            SignedTransactionHex = signedTransactionHex;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FromAddress")]
        public string FromAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SignedTransactionHex")]
        public string SignedTransactionHex { get; set; }

    }
}
