// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.EthereumCore.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PrivateWalletDataTransaction
    {
        /// <summary>
        /// Initializes a new instance of the PrivateWalletDataTransaction
        /// class.
        /// </summary>
        public PrivateWalletDataTransaction()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PrivateWalletDataTransaction
        /// class.
        /// </summary>
        public PrivateWalletDataTransaction(string value = default(string), string data = default(string), string fromAddress = default(string), string toAddress = default(string), string gasAmount = default(string), string gasPrice = default(string))
        {
            Value = value;
            Data = data;
            FromAddress = fromAddress;
            ToAddress = toAddress;
            GasAmount = gasAmount;
            GasPrice = gasPrice;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Data")]
        public string Data { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FromAddress")]
        public string FromAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ToAddress")]
        public string ToAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GasAmount")]
        public string GasAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GasPrice")]
        public string GasPrice { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Value != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(Value, "^([1-9][0-9])|0*$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "Value", "^([1-9][0-9])|0*$");
                }
            }
            if (GasAmount != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(GasAmount, "^[1-9][0-9]*$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "GasAmount", "^[1-9][0-9]*$");
                }
            }
            if (GasPrice != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(GasPrice, "^[1-9][0-9]*$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "GasPrice", "^[1-9][0-9]*$");
                }
            }
        }
    }
}
