// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.EthereumCoreClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TokenAddressTransactions
    {
        /// <summary>
        /// Initializes a new instance of the TokenAddressTransactions class.
        /// </summary>
        public TokenAddressTransactions()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TokenAddressTransactions class.
        /// </summary>
        public TokenAddressTransactions(string tokenAddress, string address, int? start = default(int?), int? count = default(int?))
        {
            TokenAddress = tokenAddress;
            Address = address;
            Start = start;
            Count = count;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tokenAddress")]
        public string TokenAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start")]
        public int? Start { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (TokenAddress == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TokenAddress");
            }
            if (Address == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Address");
            }
        }
    }
}
