// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.EthereumCore.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TransferFromDepositRequest
    {
        /// <summary>
        /// Initializes a new instance of the TransferFromDepositRequest class.
        /// </summary>
        public TransferFromDepositRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransferFromDepositRequest class.
        /// </summary>
        public TransferFromDepositRequest(string depositAddress = default(string), string tokenAddress = default(string), string destinationAddress = default(string))
        {
            DepositAddress = depositAddress;
            TokenAddress = tokenAddress;
            DestinationAddress = destinationAddress;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "depositAddress")]
        public string DepositAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tokenAddress")]
        public string TokenAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "destinationAddress")]
        public string DestinationAddress { get; set; }

    }
}
