// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.EthereumCore.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TransferWithChangeModel
    {
        /// <summary>
        /// Initializes a new instance of the TransferWithChangeModel class.
        /// </summary>
        public TransferWithChangeModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransferWithChangeModel class.
        /// </summary>
        public TransferWithChangeModel(System.Guid id, string change = default(string), string signFrom = default(string), string signTo = default(string), string coinAdapterAddress = default(string), string fromAddress = default(string), string toAddress = default(string), string amount = default(string))
        {
            Change = change;
            SignFrom = signFrom;
            SignTo = signTo;
            Id = id;
            CoinAdapterAddress = coinAdapterAddress;
            FromAddress = fromAddress;
            ToAddress = toAddress;
            Amount = amount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Change")]
        public string Change { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SignFrom")]
        public string SignFrom { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SignTo")]
        public string SignTo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CoinAdapterAddress")]
        public string CoinAdapterAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FromAddress")]
        public string FromAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ToAddress")]
        public string ToAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public string Amount { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Change != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(Change, "^[1-9][0-9]*$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "Change", "^[1-9][0-9]*$");
                }
            }
            if (Amount != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(Amount, "^[1-9][0-9]*$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "Amount", "^[1-9][0-9]*$");
                }
            }
        }
    }
}
