// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.EthereumCoreClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExistsModel
    {
        /// <summary>
        /// Initializes a new instance of the ExistsModel class.
        /// </summary>
        public ExistsModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExistsModel class.
        /// </summary>
        public ExistsModel(bool? exists = default(bool?))
        {
            Exists = exists;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exists")]
        public bool? Exists { get; set; }

    }
}
