// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SigningServiceApiCaller.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public partial class BitcoinTransactionSignRequest
    {
        /// <summary>
        /// Initializes a new instance of the BitcoinTransactionSignRequest
        /// class.
        /// </summary>
        public BitcoinTransactionSignRequest()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BitcoinTransactionSignRequest
        /// class.
        /// </summary>
        /// <param name="hashType">Possible values include: 'Undefined', 'All',
        /// 'None', 'Single', 'AnyoneCanPay'</param>
        public BitcoinTransactionSignRequest(string transaction = default(string), string hashType = default(string), IList<string> additionalSecrets = default(IList<string>))
        {
            Transaction = transaction;
            HashType = hashType;
            AdditionalSecrets = additionalSecrets;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transaction")]
        public string Transaction { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Undefined', 'All', 'None',
        /// 'Single', 'AnyoneCanPay'
        /// </summary>
        [JsonProperty(PropertyName = "hashType")]
        public string HashType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "additionalSecrets")]
        public IList<string> AdditionalSecrets { get; set; }

    }
}
