// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.EthereumCoreClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Erc20Result
    {
        /// <summary>
        /// Initializes a new instance of the Erc20Result class.
        /// </summary>
        public Erc20Result()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Erc20Result class.
        /// </summary>
        public Erc20Result(string tokenAddress = default(string), string tokenName = default(string))
        {
            TokenAddress = tokenAddress;
            TokenName = tokenName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tokenAddress")]
        public string TokenAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tokenName")]
        public string TokenName { get; set; }

    }
}
