// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.EthereumCoreClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HashResponse
    {
        /// <summary>
        /// Initializes a new instance of the HashResponse class.
        /// </summary>
        public HashResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HashResponse class.
        /// </summary>
        public HashResponse(string hashHex = default(string))
        {
            HashHex = hashHex;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hashHex")]
        public string HashHex { get; set; }

    }
}
