// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.EthereumCoreClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TokenAddressHistoryResponse
    {
        /// <summary>
        /// Initializes a new instance of the TokenAddressHistoryResponse
        /// class.
        /// </summary>
        public TokenAddressHistoryResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TokenAddressHistoryResponse
        /// class.
        /// </summary>
        public TokenAddressHistoryResponse(string tokenTransfered = default(string), string contractAddress = default(string), long? blockNumber = default(long?), string value = default(string), string gasUsed = default(string), string gasPrice = default(string), string transactionHash = default(string), string fromProperty = default(string), string to = default(string), int? blockTimestamp = default(int?), System.DateTime? blockTimeUtc = default(System.DateTime?), bool? hasError = default(bool?), int? transactionIndexInBlock = default(int?), int? messageIndex = default(int?))
        {
            TokenTransfered = tokenTransfered;
            ContractAddress = contractAddress;
            BlockNumber = blockNumber;
            Value = value;
            GasUsed = gasUsed;
            GasPrice = gasPrice;
            TransactionHash = transactionHash;
            FromProperty = fromProperty;
            To = to;
            BlockTimestamp = blockTimestamp;
            BlockTimeUtc = blockTimeUtc;
            HasError = hasError;
            TransactionIndexInBlock = transactionIndexInBlock;
            MessageIndex = messageIndex;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tokenTransfered")]
        public string TokenTransfered { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contractAddress")]
        public string ContractAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "blockNumber")]
        public long? BlockNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gasUsed")]
        public string GasUsed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gasPrice")]
        public string GasPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionHash")]
        public string TransactionHash { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "from")]
        public string FromProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "to")]
        public string To { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "blockTimestamp")]
        public int? BlockTimestamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "blockTimeUtc")]
        public System.DateTime? BlockTimeUtc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hasError")]
        public bool? HasError { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionIndexInBlock")]
        public int? TransactionIndexInBlock { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "messageIndex")]
        public int? MessageIndex { get; set; }

    }
}
