// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.EthereumCore.Client
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for EthereumCoreAPI.
    /// </summary>
    public static partial class EthereumCoreAPIExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ercTransaction'>
            /// </param>
            public static object ApiErc20BalancePost(this IEthereumCoreAPI operations, GetErcBalance ercTransaction = default(GetErcBalance))
            {
                return operations.ApiErc20BalancePostAsync(ercTransaction).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ercTransaction'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiErc20BalancePostAsync(this IEthereumCoreAPI operations, GetErcBalance ercTransaction = default(GetErcBalance), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiErc20BalancePostWithHttpMessagesAsync(ercTransaction, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userAddress'>
            /// </param>
            public static object ApiErc20depositsGet(this IEthereumCoreAPI operations, string userAddress = default(string))
            {
                return operations.ApiErc20depositsGetAsync(userAddress).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userAddress'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiErc20depositsGetAsync(this IEthereumCoreAPI operations, string userAddress = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiErc20depositsGetWithHttpMessagesAsync(userAddress, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userAddress'>
            /// </param>
            public static object ApiErc20depositsPost(this IEthereumCoreAPI operations, string userAddress = default(string))
            {
                return operations.ApiErc20depositsPostAsync(userAddress).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userAddress'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiErc20depositsPostAsync(this IEthereumCoreAPI operations, string userAddress = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiErc20depositsPostWithHttpMessagesAsync(userAddress, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ercTransaction'>
            /// </param>
            public static object ApiErc20WalletGetTransactionPost(this IEthereumCoreAPI operations, PrivateWalletErc20Transaction ercTransaction = default(PrivateWalletErc20Transaction))
            {
                return operations.ApiErc20WalletGetTransactionPostAsync(ercTransaction).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ercTransaction'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiErc20WalletGetTransactionPostAsync(this IEthereumCoreAPI operations, PrivateWalletErc20Transaction ercTransaction = default(PrivateWalletErc20Transaction), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiErc20WalletGetTransactionPostWithHttpMessagesAsync(ercTransaction, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ethTransactionSigned'>
            /// </param>
            public static object ApiErc20WalletSubmitTransactionPost(this IEthereumCoreAPI operations, PrivateWalletEthSignedTransaction ethTransactionSigned = default(PrivateWalletEthSignedTransaction))
            {
                return operations.ApiErc20WalletSubmitTransactionPostAsync(ethTransactionSigned).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ethTransactionSigned'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiErc20WalletSubmitTransactionPostAsync(this IEthereumCoreAPI operations, PrivateWalletEthSignedTransaction ethTransactionSigned = default(PrivateWalletEthSignedTransaction), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiErc20WalletSubmitTransactionPostWithHttpMessagesAsync(ethTransactionSigned, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static object ApiExchangeCashoutPost(this IEthereumCoreAPI operations, CashoutModel model = default(CashoutModel))
            {
                return operations.ApiExchangeCashoutPostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiExchangeCashoutPostAsync(this IEthereumCoreAPI operations, CashoutModel model = default(CashoutModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiExchangeCashoutPostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='guid'>
            /// </param>
            public static CheckIdResponse ApiExchangeCheckIdByGuidGet(this IEthereumCoreAPI operations, System.Guid guid)
            {
                return operations.ApiExchangeCheckIdByGuidGetAsync(guid).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='guid'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CheckIdResponse> ApiExchangeCheckIdByGuidGetAsync(this IEthereumCoreAPI operations, System.Guid guid, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiExchangeCheckIdByGuidGetWithHttpMessagesAsync(guid, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static object ApiExchangeTransferPost(this IEthereumCoreAPI operations, TransferModel model = default(TransferModel))
            {
                return operations.ApiExchangeTransferPostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiExchangeTransferPostAsync(this IEthereumCoreAPI operations, TransferModel model = default(TransferModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiExchangeTransferPostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static object ApiExchangeCheckSignPost(this IEthereumCoreAPI operations, CheckSignModel model = default(CheckSignModel))
            {
                return operations.ApiExchangeCheckSignPostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiExchangeCheckSignPostAsync(this IEthereumCoreAPI operations, CheckSignModel model = default(CheckSignModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiExchangeCheckSignPostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static object ApiExchangeTransferWithChangePost(this IEthereumCoreAPI operations, TransferWithChangeModel model = default(TransferWithChangeModel))
            {
                return operations.ApiExchangeTransferWithChangePostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiExchangeTransferWithChangePostAsync(this IEthereumCoreAPI operations, TransferWithChangeModel model = default(TransferWithChangeModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiExchangeTransferWithChangePostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static object ApiExchangeCheckPendingTransactionPost(this IEthereumCoreAPI operations, CheckPendingModel model = default(CheckPendingModel))
            {
                return operations.ApiExchangeCheckPendingTransactionPostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiExchangeCheckPendingTransactionPostAsync(this IEthereumCoreAPI operations, CheckPendingModel model = default(CheckPendingModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiExchangeCheckPendingTransactionPostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static object ApiExchangeEstimateCashoutGasPost(this IEthereumCoreAPI operations, TransferModel model = default(TransferModel))
            {
                return operations.ApiExchangeEstimateCashoutGasPostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiExchangeEstimateCashoutGasPostAsync(this IEthereumCoreAPI operations, TransferModel model = default(TransferModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiExchangeEstimateCashoutGasPostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static ListResultExternalTokenModel ApiExternalTokenGet(this IEthereumCoreAPI operations)
            {
                return operations.ApiExternalTokenGetAsync().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ListResultExternalTokenModel> ApiExternalTokenGetAsync(this IEthereumCoreAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiExternalTokenGetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='externalTokenAddress'>
            /// </param>
            public static ExternalTokenModel ApiExternalTokenByExternalTokenAddressGet(this IEthereumCoreAPI operations, string externalTokenAddress)
            {
                return operations.ApiExternalTokenByExternalTokenAddressGetAsync(externalTokenAddress).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='externalTokenAddress'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ExternalTokenModel> ApiExternalTokenByExternalTokenAddressGetAsync(this IEthereumCoreAPI operations, string externalTokenAddress, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiExternalTokenByExternalTokenAddressGetWithHttpMessagesAsync(externalTokenAddress, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static ExternalTokenModel ApiExternalTokenCreatePost(this IEthereumCoreAPI operations, CreateExternalTokenModel model = default(CreateExternalTokenModel))
            {
                return operations.ApiExternalTokenCreatePostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ExternalTokenModel> ApiExternalTokenCreatePostAsync(this IEthereumCoreAPI operations, CreateExternalTokenModel model = default(CreateExternalTokenModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiExternalTokenCreatePostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static ExternalTokenModel ApiExternalTokenIssuePost(this IEthereumCoreAPI operations, IssueTokensModel model = default(IssueTokensModel))
            {
                return operations.ApiExternalTokenIssuePostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ExternalTokenModel> ApiExternalTokenIssuePostAsync(this IEthereumCoreAPI operations, IssueTokensModel model = default(IssueTokensModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiExternalTokenIssuePostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='externalTokenAddress'>
            /// </param>
            /// <param name='ownerAddress'>
            /// </param>
            public static BalanceModel ApiExternalTokenBalanceByExternalTokenAddressByOwnerAddressGet(this IEthereumCoreAPI operations, string externalTokenAddress, string ownerAddress)
            {
                return operations.ApiExternalTokenBalanceByExternalTokenAddressByOwnerAddressGetAsync(externalTokenAddress, ownerAddress).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='externalTokenAddress'>
            /// </param>
            /// <param name='ownerAddress'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<BalanceModel> ApiExternalTokenBalanceByExternalTokenAddressByOwnerAddressGetAsync(this IEthereumCoreAPI operations, string externalTokenAddress, string ownerAddress, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiExternalTokenBalanceByExternalTokenAddressByOwnerAddressGetWithHttpMessagesAsync(externalTokenAddress, ownerAddress, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static GasPriceModel ApiGasPriceGet(this IEthereumCoreAPI operations)
            {
                return operations.ApiGasPriceGetAsync().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<GasPriceModel> ApiGasPriceGetAsync(this IEthereumCoreAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiGasPriceGetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static void ApiGasPricePost(this IEthereumCoreAPI operations, GasPriceModel model = default(GasPriceModel))
            {
                operations.ApiGasPricePostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ApiGasPricePostAsync(this IEthereumCoreAPI operations, GasPriceModel model = default(GasPriceModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.ApiGasPricePostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static object ApiHashCalculateAndGetIdPost(this IEthereumCoreAPI operations, BaseCoinRequestParametersModel model = default(BaseCoinRequestParametersModel))
            {
                return operations.ApiHashCalculateAndGetIdPostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiHashCalculateAndGetIdPostAsync(this IEthereumCoreAPI operations, BaseCoinRequestParametersModel model = default(BaseCoinRequestParametersModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiHashCalculateAndGetIdPostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static object ApiHashCalculatePost(this IEthereumCoreAPI operations, BaseCoinRequestModel model = default(BaseCoinRequestModel))
            {
                return operations.ApiHashCalculatePostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiHashCalculatePostAsync(this IEthereumCoreAPI operations, BaseCoinRequestModel model = default(BaseCoinRequestModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiHashCalculatePostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='hotWalletCashout'>
            /// </param>
            public static ApiException ApiHotWalletPost(this IEthereumCoreAPI operations, HotWalletCashoutRequest hotWalletCashout = default(HotWalletCashoutRequest))
            {
                return operations.ApiHotWalletPostAsync(hotWalletCashout).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='hotWalletCashout'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ApiException> ApiHotWalletPostAsync(this IEthereumCoreAPI operations, HotWalletCashoutRequest hotWalletCashout = default(HotWalletCashoutRequest), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiHotWalletPostWithHttpMessagesAsync(hotWalletCashout, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='transactionHash'>
            /// </param>
            public static object ApiInternalMessagesTxHashByTransactionHashPost(this IEthereumCoreAPI operations, string transactionHash)
            {
                return operations.ApiInternalMessagesTxHashByTransactionHashPostAsync(transactionHash).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='transactionHash'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiInternalMessagesTxHashByTransactionHashPostAsync(this IEthereumCoreAPI operations, string transactionHash, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiInternalMessagesTxHashByTransactionHashPostWithHttpMessagesAsync(transactionHash, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='addressTransactions'>
            /// </param>
            public static object ApiInternalMessagesPost(this IEthereumCoreAPI operations, AddressTransactions addressTransactions = default(AddressTransactions))
            {
                return operations.ApiInternalMessagesPostAsync(addressTransactions).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='addressTransactions'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiInternalMessagesPostAsync(this IEthereumCoreAPI operations, AddressTransactions addressTransactions = default(AddressTransactions), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiInternalMessagesPostWithHttpMessagesAsync(addressTransactions, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static object IsAlive(this IEthereumCoreAPI operations)
            {
                return operations.IsAliveAsync().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> IsAliveAsync(this IEthereumCoreAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.IsAliveWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='apiKey'>
            /// Api key
            /// </param>
            /// <param name='userAddress'>
            /// </param>
            public static object ApiLykkePayErc20depositsGet(this IEthereumCoreAPI operations, string apiKey, string userAddress = default(string))
            {
                return operations.ApiLykkePayErc20depositsGetAsync(apiKey, userAddress).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='apiKey'>
            /// Api key
            /// </param>
            /// <param name='userAddress'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiLykkePayErc20depositsGetAsync(this IEthereumCoreAPI operations, string apiKey, string userAddress = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiLykkePayErc20depositsGetWithHttpMessagesAsync(apiKey, userAddress, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='apiKey'>
            /// Api key
            /// </param>
            /// <param name='userAddress'>
            /// </param>
            public static object ApiLykkePayErc20depositsPost(this IEthereumCoreAPI operations, string apiKey, string userAddress = default(string))
            {
                return operations.ApiLykkePayErc20depositsPostAsync(apiKey, userAddress).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='apiKey'>
            /// Api key
            /// </param>
            /// <param name='userAddress'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiLykkePayErc20depositsPostAsync(this IEthereumCoreAPI operations, string apiKey, string userAddress = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiLykkePayErc20depositsPostWithHttpMessagesAsync(apiKey, userAddress, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='apiKey'>
            /// Api key
            /// </param>
            /// <param name='request'>
            /// </param>
            public static object ApiLykkePayErc20depositsTransferPost(this IEthereumCoreAPI operations, string apiKey, TransferFromDepositRequest request = default(TransferFromDepositRequest))
            {
                return operations.ApiLykkePayErc20depositsTransferPostAsync(apiKey, request).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='apiKey'>
            /// Api key
            /// </param>
            /// <param name='request'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiLykkePayErc20depositsTransferPostAsync(this IEthereumCoreAPI operations, string apiKey, TransferFromDepositRequest request = default(TransferFromDepositRequest), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiLykkePayErc20depositsTransferPostWithHttpMessagesAsync(apiKey, request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ethTransaction'>
            /// </param>
            public static object ApiPrivateWalletGetTransactionPost(this IEthereumCoreAPI operations, PrivateWalletEthTransaction ethTransaction = default(PrivateWalletEthTransaction))
            {
                return operations.ApiPrivateWalletGetTransactionPostAsync(ethTransaction).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ethTransaction'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiPrivateWalletGetTransactionPostAsync(this IEthereumCoreAPI operations, PrivateWalletEthTransaction ethTransaction = default(PrivateWalletEthTransaction), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiPrivateWalletGetTransactionPostWithHttpMessagesAsync(ethTransaction, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ethTransactionSigned'>
            /// </param>
            public static object ApiPrivateWalletSubmitTransactionPost(this IEthereumCoreAPI operations, PrivateWalletEthSignedTransaction ethTransactionSigned = default(PrivateWalletEthSignedTransaction))
            {
                return operations.ApiPrivateWalletSubmitTransactionPostAsync(ethTransactionSigned).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ethTransactionSigned'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiPrivateWalletSubmitTransactionPostAsync(this IEthereumCoreAPI operations, PrivateWalletEthSignedTransaction ethTransactionSigned = default(PrivateWalletEthSignedTransaction), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiPrivateWalletSubmitTransactionPostWithHttpMessagesAsync(ethTransactionSigned, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ethTransactionSigned'>
            /// </param>
            public static object ApiPrivateWalletEstimateTransactionPost(this IEthereumCoreAPI operations, PrivateWalletEthSignedTransaction ethTransactionSigned = default(PrivateWalletEthSignedTransaction))
            {
                return operations.ApiPrivateWalletEstimateTransactionPostAsync(ethTransactionSigned).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ethTransactionSigned'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiPrivateWalletEstimateTransactionPostAsync(this IEthereumCoreAPI operations, PrivateWalletEthSignedTransaction ethTransactionSigned = default(PrivateWalletEthSignedTransaction), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiPrivateWalletEstimateTransactionPostWithHttpMessagesAsync(ethTransactionSigned, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='address'>
            /// </param>
            public static object ApiRpcGetBalanceByAddressGet(this IEthereumCoreAPI operations, string address)
            {
                return operations.ApiRpcGetBalanceByAddressGetAsync(address).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='address'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiRpcGetBalanceByAddressGetAsync(this IEthereumCoreAPI operations, string address, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiRpcGetBalanceByAddressGetWithHttpMessagesAsync(address, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static object ApiRpcGetNetworkGasPriceGet(this IEthereumCoreAPI operations)
            {
                return operations.ApiRpcGetNetworkGasPriceGetAsync().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiRpcGetNetworkGasPriceGetAsync(this IEthereumCoreAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiRpcGetNetworkGasPriceGetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='addressTransactions'>
            /// </param>
            public static object ApiTransactionsPost(this IEthereumCoreAPI operations, AddressTransactions addressTransactions = default(AddressTransactions))
            {
                return operations.ApiTransactionsPostAsync(addressTransactions).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='addressTransactions'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiTransactionsPostAsync(this IEthereumCoreAPI operations, AddressTransactions addressTransactions = default(AddressTransactions), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiTransactionsPostWithHttpMessagesAsync(addressTransactions, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='transactionHash'>
            /// </param>
            public static object ApiTransactionsTxHashByTransactionHashPost(this IEthereumCoreAPI operations, string transactionHash)
            {
                return operations.ApiTransactionsTxHashByTransactionHashPostAsync(transactionHash).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='transactionHash'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiTransactionsTxHashByTransactionHashPostAsync(this IEthereumCoreAPI operations, string transactionHash, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiTransactionsTxHashByTransactionHashPostWithHttpMessagesAsync(transactionHash, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='addressTransactions'>
            /// </param>
            public static object ApiTransactionsHistoryPost(this IEthereumCoreAPI operations, AddressTransactions addressTransactions = default(AddressTransactions))
            {
                return operations.ApiTransactionsHistoryPostAsync(addressTransactions).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='addressTransactions'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiTransactionsHistoryPostAsync(this IEthereumCoreAPI operations, AddressTransactions addressTransactions = default(AddressTransactions), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiTransactionsHistoryPostWithHttpMessagesAsync(addressTransactions, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='addressTransactions'>
            /// </param>
            public static object ApiTransactionsErcHistoryPost(this IEthereumCoreAPI operations, TokenAddressTransactions addressTransactions = default(TokenAddressTransactions))
            {
                return operations.ApiTransactionsErcHistoryPostAsync(addressTransactions).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='addressTransactions'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiTransactionsErcHistoryPostAsync(this IEthereumCoreAPI operations, TokenAddressTransactions addressTransactions = default(TokenAddressTransactions), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiTransactionsErcHistoryPostWithHttpMessagesAsync(addressTransactions, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static object ApiTransitionCreatePost(this IEthereumCoreAPI operations, CreateTransitionContractModel model = default(CreateTransitionContractModel))
            {
                return operations.ApiTransitionCreatePostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiTransitionCreatePostAsync(this IEthereumCoreAPI operations, CreateTransitionContractModel model = default(CreateTransitionContractModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiTransitionCreatePostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userAddress'>
            /// </param>
            /// <param name='coinAdapterAddress'>
            /// </param>
            public static object ApiTransitionContractAddressByUserAddressByCoinAdapterAddressGet(this IEthereumCoreAPI operations, string userAddress, string coinAdapterAddress)
            {
                return operations.ApiTransitionContractAddressByUserAddressByCoinAdapterAddressGetAsync(userAddress, coinAdapterAddress).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userAddress'>
            /// </param>
            /// <param name='coinAdapterAddress'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiTransitionContractAddressByUserAddressByCoinAdapterAddressGetAsync(this IEthereumCoreAPI operations, string userAddress, string coinAdapterAddress, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiTransitionContractAddressByUserAddressByCoinAdapterAddressGetWithHttpMessagesAsync(userAddress, coinAdapterAddress, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ethAddress'>
            /// </param>
            public static object ApiValidationGet(this IEthereumCoreAPI operations, string ethAddress = default(string))
            {
                return operations.ApiValidationGetAsync(ethAddress).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ethAddress'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiValidationGetAsync(this IEthereumCoreAPI operations, string ethAddress = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiValidationGetWithHttpMessagesAsync(ethAddress, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='address'>
            /// </param>
            public static object ApiWhiteListByAddressGet(this IEthereumCoreAPI operations, string address)
            {
                return operations.ApiWhiteListByAddressGetAsync(address).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='address'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiWhiteListByAddressGetAsync(this IEthereumCoreAPI operations, string address, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiWhiteListByAddressGetWithHttpMessagesAsync(address, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='address'>
            /// </param>
            public static ApiException ApiWhiteListByAddressDelete(this IEthereumCoreAPI operations, string address)
            {
                return operations.ApiWhiteListByAddressDeleteAsync(address).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='address'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ApiException> ApiWhiteListByAddressDeleteAsync(this IEthereumCoreAPI operations, string address, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiWhiteListByAddressDeleteWithHttpMessagesAsync(address, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static ApiException ApiWhiteListPost(this IEthereumCoreAPI operations, EthereumAddressRequest model = default(EthereumAddressRequest))
            {
                return operations.ApiWhiteListPostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ApiException> ApiWhiteListPostAsync(this IEthereumCoreAPI operations, EthereumAddressRequest model = default(EthereumAddressRequest), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiWhiteListPostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static ListResultCoinResult ApiCoinAdapterGet(this IEthereumCoreAPI operations)
            {
                return operations.ApiCoinAdapterGetAsync().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ListResultCoinResult> ApiCoinAdapterGetAsync(this IEthereumCoreAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiCoinAdapterGetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='adapterAddress'>
            /// </param>
            public static ExistsModel ApiCoinAdapterExistsByAdapterAddressGet(this IEthereumCoreAPI operations, string adapterAddress)
            {
                return operations.ApiCoinAdapterExistsByAdapterAddressGetAsync(adapterAddress).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='adapterAddress'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ExistsModel> ApiCoinAdapterExistsByAdapterAddressGetAsync(this IEthereumCoreAPI operations, string adapterAddress, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiCoinAdapterExistsByAdapterAddressGetWithHttpMessagesAsync(adapterAddress, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            public static CoinResult ApiCoinAdapterByIdGet(this IEthereumCoreAPI operations, string id)
            {
                return operations.ApiCoinAdapterByIdGetAsync(id).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CoinResult> ApiCoinAdapterByIdGetAsync(this IEthereumCoreAPI operations, string id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiCoinAdapterByIdGetWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='adapterAddress'>
            /// </param>
            public static CoinResult ApiCoinAdapterAddressByAdapterAddressGet(this IEthereumCoreAPI operations, string adapterAddress)
            {
                return operations.ApiCoinAdapterAddressByAdapterAddressGetAsync(adapterAddress).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='adapterAddress'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<CoinResult> ApiCoinAdapterAddressByAdapterAddressGetAsync(this IEthereumCoreAPI operations, string adapterAddress, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiCoinAdapterAddressByAdapterAddressGetWithHttpMessagesAsync(adapterAddress, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            public static RegisterResponse ApiCoinAdapterCreatePost(this IEthereumCoreAPI operations, CreateAssetModel model = default(CreateAssetModel))
            {
                return operations.ApiCoinAdapterCreatePostAsync(model).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='model'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<RegisterResponse> ApiCoinAdapterCreatePostAsync(this IEthereumCoreAPI operations, CreateAssetModel model = default(CreateAssetModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiCoinAdapterCreatePostWithHttpMessagesAsync(model, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='coinAdapterAddress'>
            /// </param>
            /// <param name='userAddress'>
            /// </param>
            public static object ApiCoinAdapterBalanceByCoinAdapterAddressByUserAddressGet(this IEthereumCoreAPI operations, string coinAdapterAddress, string userAddress)
            {
                return operations.ApiCoinAdapterBalanceByCoinAdapterAddressByUserAddressGetAsync(coinAdapterAddress, userAddress).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='coinAdapterAddress'>
            /// </param>
            /// <param name='userAddress'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ApiCoinAdapterBalanceByCoinAdapterAddressByUserAddressGetAsync(this IEthereumCoreAPI operations, string coinAdapterAddress, string userAddress, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiCoinAdapterBalanceByCoinAdapterAddressByUserAddressGetWithHttpMessagesAsync(coinAdapterAddress, userAddress, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
